use clap::Args;
use color_eyre::eyre::{eyre, Result};
use std::process::Command;

#[derive(Args)]
pub struct LintArgs {
    /// Auto-fix formatting issues
    #[arg(long)]
    pub fix: bool,

    /// Install git pre-commit hooks
    #[arg(long)]
    pub install_hooks: bool,

    /// Uninstall git pre-commit hooks
    #[arg(long)]
    pub uninstall_hooks: bool,

    /// Only check staged files (used by pre-commit hook)
    #[arg(long)]
    pub staged_only: bool,
}

pub fn run(args: &LintArgs) -> Result<()> {
    if args.install_hooks {
        return install_hooks();
    }

    if args.uninstall_hooks {
        return uninstall_hooks();
    }

    // Step 1: Format
    println!("==> Checking formatting...");
    let mut fmt_args = vec!["fmt", "--"];
    if !args.fix {
        fmt_args.push("--check");
    }
    run_cargo(&fmt_args)?;

    // Step 2: Check
    println!("==> Checking compilation...");
    run_cargo(&["check", "--workspace"])?;

    // Step 3: Clippy
    println!("==> Running clippy...");
    run_cargo(&[
        "clippy",
        "--workspace",
        "--all-targets",
        "--",
        "-D",
        "warnings",
    ])?;

    // Step 4: Test
    println!("==> Running tests...");
    run_cargo(&["test", "--workspace"])?;

    // Step 5: File length check
    println!("==> Checking file lengths...");
    check_file_lengths()?;

    println!("==> All checks passed!");
    Ok(())
}

fn run_cargo(args: &[&str]) -> Result<()> {
    let status = Command::new("cargo")
        .args(args)
        .status()
        .map_err(|e| eyre!("Failed to run cargo: {e}"))?;

    if !status.success() {
        return Err(eyre!("cargo {} failed", args.join(" ")));
    }
    Ok(())
}

fn check_file_lengths() -> Result<()> {
    let max_lines = 1000;
    let mut violations = Vec::new();

    for entry in glob::glob("crates/*/src/**/*.rs")
        .into_iter()
        .flatten()
        .flatten()
    {
        let content = std::fs::read_to_string(&entry)
            .map_err(|e| eyre!("Failed to read {}: {e}", entry.display()))?;
        let line_count = content.lines().count();
        if line_count > max_lines {
            violations.push(format!("  {} ({line_count} lines)", entry.display()));
        }
    }

    if !violations.is_empty() {
        return Err(eyre!(
            "Files exceeding {max_lines} lines:\n{}",
            violations.join("\n")
        ));
    }
    Ok(())
}

fn install_hooks() -> Result<()> {
    let hooks_dir = std::path::Path::new(".git/hooks");
    if !hooks_dir.exists() {
        return Err(eyre!(
            ".git/hooks directory not found. Are you in the repo root?"
        ));
    }

    let hook_path = hooks_dir.join("pre-commit");
    let hook_content = "#!/bin/sh\n# Generated by: cargo xtask lint --install-hooks\n# Runs all code quality checks via cargo xtask lint\nexec cargo xtask lint --staged-only\n";

    std::fs::write(&hook_path, hook_content).map_err(|e| eyre!("Failed to write hook: {e}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&hook_path, std::fs::Permissions::from_mode(0o755))
            .map_err(|e| eyre!("Failed to set hook permissions: {e}"))?;
    }

    println!("Pre-commit hook installed at {}", hook_path.display());
    Ok(())
}

fn uninstall_hooks() -> Result<()> {
    let hook_path = std::path::Path::new(".git/hooks/pre-commit");
    if hook_path.exists() {
        std::fs::remove_file(hook_path).map_err(|e| eyre!("Failed to remove hook: {e}"))?;
        println!("Pre-commit hook removed.");
    } else {
        println!("No pre-commit hook found.");
    }
    Ok(())
}
